
name: Build APK Without Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2"

      
      - name: Compile Java
        run: |
          mkdir -p build/classes
          find ./src -name "*.java" > sources.txt
          javac -d build/classes @sources.txt

      
      - name: Convert to DEX
        run: |
          $HOME/android-sdk/cmdline-tools/tools/bin/d8 --output build build/classes

      
      - name: Package APK
        run: |
          mkdir -p build/apk
          $HOME/android-sdk/cmdline-tools/tools/bin/aapt package -f -M AndroidManifest.xml -S res -I $HOME/android-sdk/platforms/android-33/android.jar -F build/apk/unsigned.apk
          cd build/apk
          zip -u unsigned.apk ../classes.dex
          cd ../../

      
      - name: Sign APK
        run: |
          keytool -genkeypair -v -keystore debug.keystore -alias mykey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Demo, OU=Dev, O=Test, L=City, ST=State, C=US"
          jarsigner -keystore debug.keystore -storepass android -keypass android build/apk/unsigned.apk mykey

      
      - name: Align APK
        run: |
          $HOME/android-sdk/cmdline-tools/tools/bin/zipalign -v 4 build/apk/unsigned.apk build/apk/MyApp.apk

      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp.apk
          path: build/apk/MyApp.apk
